Repository sniperfactory-official/sfac-lms-team-b, pull requests merged in 2023-07, with the labels that each got.

#5 Team5 style/assignment detail
  public/images/img_dummy_200x200.webp
  public/next.svg
  public/vercel.svg
  src/app/assignment/components/Modal.tsx
  src/app/assignment/components/ProfileImage.tsx
  src/app/assignment/components/StudentViewCard.tsx
  src/app/assignment/components/SubmitAssignmentWithFile.tsx
  src/app/assignment/components/SubmitAssignmentWithLink.tsx
  src/app/assignment/components/TeacherViewCard.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/app/assignment/detail/page.tsx
  src/components/EmptyContents.tsx
Labels: enhancement

#7 Team5 feat/assignment feedback
  src/app/assignment/components/CreateAssignment.tsx
  src/app/assignment/components/Feedback.tsx
  src/app/assignment/components/LeftNav.tsx
  src/app/assignment/detail/page.tsx
  src/app/assignment/layout.tsx
  src/app/assignment/list/page.tsx
  src/hooks/reactQuery/useCreateAssignment.ts
  src/hooks/reactQuery/useGetAssignment.ts
  src/hooks/reactQuery/useSubmittedAssignment.ts
  src/utils/firebase.ts
Labels: enhancement

#54 Style: 강의장 레이아웃 구현
  src/app/classroom/[lectureId]/page.tsx
  src/components/lecture/LectureComment.tsx
  src/components/lecture/LectureHeader.tsx
  src/components/lecture/LectureNavigation.tsx
  src/components/lecture/typesOf/TypeOfLecture.tsx
  src/redux/store.tsx
Labels: Style, team6

#55 Feat: 강의장 커뮤니티 댓글/답글 기능 구현
  src/components/classroomModal/comment/Comment.tsx
  src/components/classroomModal/comment/CommentForm.tsx
  src/components/classroomModal/comment/ReplySection.tsx
  src/components/lecture/CommentsSection.tsx
Labels: Feat, team6

#56 Feat: DB에서 강의정보 가저와서 타입에 따른 강의장 랜더링 기능 구현
  src/components/lecture/typesOf/LinkLecture.tsx
  src/components/lecture/typesOf/NoteLecture.tsx
  src/components/lecture/typesOf/VideoLecture.tsx
  src/hooks/lecture/useGetLectureInfo.tsx
  src/types/firebase.Types.ts
  src/utils/firebase.ts
Labels: Feat, team6

#59 Feat: 클래스룸의 모든 모달창 공통 레이아웃 구현
  src/components/classroomModal/common/Layout.tsx
Labels: Feat, Style, team6

#64 Style: 클래스룸 강의 추가 모달창 공통 컴포넌트 구현
  src/components/classroomModal/common/LectureTitle.tsx
  src/components/classroomModal/common/ModalFooter.tsx
  src/components/classroomModal/common/ModalHeader.tsx
  src/components/classroomModal/common/ModalSubmitButton.tsx
Labels: Style, team6

#65 Feat: assignment hook 기능구현 및 submitted hook 일부 기능구현
  src/app/assignment/components/Feedback.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  src/hooks/reactQuery/index.tsx
  src/utils/firebase.ts
Labels: Feat, Rename, team5

#66 Feat: 클래스룸 모든 모달창 visibility 상태관리 로직 구현
  src/hooks/lecture/useClassroomModal.tsx
  src/redux/slice/classroomModalSlice.tsx
  src/redux/store.tsx
Labels: Feat, team6

#62 Feat: 강의장 Header 랜더링 구현
  public/images/arrow-left.svg
  public/images/arrow-right.svg
  public/images/backward-step.svg
  public/images/forward-step.svg
  src/app/classroom/[lectureId]/page.tsx
  src/components/lecture/LectureHeader.tsx
  src/utils/timestampToDate.ts
Labels: Feat, team6

#67 Feat: assignment 만들기
  public/images/img_dummy_200x200.webp
  public/next.svg
  public/vercel.svg
  src/app/assignment/components/CreateAssignment.tsx
  src/app/assignment/components/Modal.tsx
  src/app/assignment/components/ProfileImage.tsx
  src/app/assignment/components/StudentViewCard.tsx
  src/app/assignment/components/SubmitAssignmentWithFile.tsx
  src/app/assignment/components/SubmitAssignmentWithLink.tsx
  src/app/assignment/components/TeacherViewCard.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/app/assignment/detail/page.tsx
  src/components/EmptyContents.tsx
Labels: Feat

#68 Feat: 과제 네비게이션 및 리스트 기본 레이아웃
  src/app/assignment/components/LeftNav.tsx
  src/app/assignment/list/page.tsx
  src/hooks/reactQuery/useSubmittedAssignment.ts
Labels: Feat, team5

#69 Feat: 과제 파일, 링크 제출 기능 및 토스트UI 컴포넌트 작업 등
  src/app/assignment/components/Modal.tsx
  src/app/assignment/components/StudentViewCard.tsx
  src/app/assignment/components/SubmitAssignmentWithFile.tsx
  src/app/assignment/components/SubmitAssignmentWithLink.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/components/GlobalToast.tsx
  src/components/PageToast.tsx
Labels: Feat, team5

#71 Fix: 이미지 파일 변경 및 모달 header 컴포넌트에 선택적 프로퍼티 적용
  public/images/arrow-right.svg
  src/components/classroomModal/common/ModalHeader.tsx
  src/hooks/lecture/useClassroomModal.tsx
Labels: bug, team6

#73 Docs: 이미지 파일 추가
  public/images/link.svg
  public/images/note.svg
  public/images/video.svg
Labels: Docs

#74 Feat: 강의 기간 설정 / 공개 여부 기능 구현
  package.json
  src/app/classroom/page.tsx
  src/components/classroomModal/common/LectureSetting.tsx
  src/components/classroomModal/common/ModalFooter.tsx
  src/components/classroomModal/common/ModalSubmitButton.tsx
Labels: Feat, team6

#77 Feat: /classroom data fetch & render
  src/app/classroom/page.tsx
  src/components/classroom/Aside.tsx
  src/components/classroom/ClassContent.tsx
  src/components/classroom/MOCK_DATA.ts
  src/components/classroom/aside/AsideButton.tsx
  src/components/classroom/aside/CourseList.tsx
  src/components/classroom/aside/Element.tsx
  src/components/classroom/aside/SectionButton.tsx
  src/components/classroom/aside/SectionHandlerButton.tsx
  src/components/classroom/main/ContentCard.tsx
  src/constants/queryKey.ts
  src/hooks/queries/useGetCourseList.ts
  src/utils/firebase.ts
Labels: Feat, team6

#78 Feat: 클래스룸 노트 모달 및 마크다운 에디션 구현
  package.json
  src/components/classroom/ClassContent.tsx
  src/components/classroomModal/createLecture/AddNoteModal.tsx
  src/components/classroomModal/createLecture/NoteSction.tsx
  yarn.lock
Labels: Feat, Style, team6

#80 Feat: 강의장 댓글 커뮤니티 기능 구현
  src/app/classroom/[lectureId]/page.tsx
  src/components/classroomModal/comment/Comment.tsx
  src/components/classroomModal/comment/CommentForm.tsx
  src/components/classroomModal/comment/ReplySection.tsx
  src/components/lecture/CommentsSection.tsx
  src/components/lecture/LectureComment.tsx
  src/components/lectureRoom/CommentsSection.tsx
  src/components/lectureRoom/LectureComment.tsx
  src/components/lectureRoom/LectureHeader.tsx
  src/components/lectureRoom/LectureNavigation.tsx
  src/components/lectureRoom/typesOf/LinkLecture.tsx
  src/components/lectureRoom/typesOf/NoteLecture.tsx
  src/components/lectureRoom/typesOf/TypeOfLecture.tsx
  src/components/lectureRoom/typesOf/VideoLecture.tsx
  src/hooks/lecture/useGetLectureCommentId.tsx
  src/hooks/lecture/useGetLectureComments.tsx
  src/hooks/lecture/useGetLectureReplies.tsx
  src/hooks/lecture/useGetLectureReply.tsx
  src/hooks/useLectureComment.tsx
  src/utils/getTime.ts
  src/utils/timestampToDate.ts
Labels: Feat, team6

#81 Update: 링크 모달 수정
  src/components/classroomModal/common/LectureSetting.tsx
  src/components/classroomModal/common/ModalSubmitButton.tsx
  src/components/classroomModal/createLecture/AddLinkModal.tsx
  src/components/classroomModal/createLecture/MakeLectureModal.tsx
  src/redux/slice/linkContentSlice.tsx
Labels: Style, Update, team6

#87 Update: date picker 수정, toggle input 수정
  src/components/classroomModal/common/LectureSetting.tsx
Labels: Update, team6

#89 Team5 작업 내용
  public/images/img_dummy_200x200.webp
  public/next.svg
  public/vercel.svg
  src/app/assignment/components/CreateAssignment.tsx
  src/app/assignment/components/Feedback.tsx
  src/app/assignment/components/LeftNav.tsx
  src/app/assignment/components/Modal.tsx
  src/app/assignment/components/ProfileImage.tsx
  src/app/assignment/components/StudentViewCard.tsx
  src/app/assignment/components/SubmitAssignmentWithFile.tsx
  src/app/assignment/components/SubmitAssignmentWithLink.tsx
  src/app/assignment/components/TeacherViewCard.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/app/assignment/detail/page.tsx
  src/app/assignment/list/page.tsx
  src/components/EmptyContents.tsx
  src/components/GlobalToast.tsx
  src/components/PageToast.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  src/hooks/reactQuery/useSubmittedAssignment.ts
  src/utils/firebase.ts
Labels: team5

#95 Refactor: create assignment refactoring
  .DS_Store
  .gitignore
  src/app/assignment/components/CreateAssignment.tsx
  src/app/assignment/components/CreateAssignments.tsx
  src/app/assignment/components/LeftNav.tsx
Labels: Refactor

#98 Team6 fix/issue97
  package.json
  src/app/classroom/page.tsx
  src/components/Header/Tab.tsx
  src/components/classroom/Aside.tsx
  src/components/classroom/ClassContent.tsx
  src/utils/firebase.ts
  src/utils/getTime.ts
  yarn.lock
Labels: Style, Fix, team6

#96 Team5 feat/assignment navlist
  package.json
  src/app/assignment/components/ListContent.tsx
  src/app/assignment/list/page.tsx
  yarn.lock
Labels: Feat, team5

#100 Refactor: 유저정보 분기처리 및 코드 가독성 개선, 전체과제 이동버튼 활성화
  src/app/assignment/components/LeftNav.tsx
  src/app/assignment/components/LeftNavContent.tsx
  src/app/assignment/components/ListContent.tsx
  src/app/assignment/list/page.tsx
Labels: Refactor, Test

#102 Refactor: LectureComments 컬렉션에 맞게 강의 커뮤니티 코드 수정
  src/components/classroomModal/comment/Comment.tsx
  src/components/classroomModal/comment/ReplySection.tsx
  src/components/lectureRoom/CommentsSection.tsx
  src/components/lectureRoom/LectureComment.tsx
  src/hooks/lecture/useGetComments.tsx
  src/hooks/lecture/useGetLectureCommentId.tsx
  src/hooks/lecture/useGetLectureComments.tsx
  src/hooks/lecture/useGetLectureReplies.tsx
  src/hooks/lecture/useGetLectureReply.tsx
Labels: Refactor, team6

#104 Rename: 과제 컴포넌트 파일명 및 폴더 구조 변경, 경로 수정
  .DS_Store
  .gitignore
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/components/CreateAssignment.tsx
  src/app/assignment/components/LeftNav.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/app/assignment/layout.tsx
  src/app/assignment/list/page.tsx
  src/app/assignment/page.tsx
  src/hooks/mutation/useDeleteSubmittedAssignment.ts
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  yarn.lock
Labels: Rename

#108 Style: 시맨틱 마크업 및 전체적인 레이아웃 구조 수정
  public/images/icon_target.svg
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/layout.tsx
  src/app/assignment/page.tsx
Labels: Style, team5

#106 Feat: 강의장 댓글 기능 구현 및 로그인 상태에 따른 수정/삭제 UI 구현
  src/components/classroomModal/comment/Comment.tsx
  src/components/classroomModal/comment/CommentForm.tsx
  src/components/lectureRoom/LectureComment.tsx
  src/hooks/lecture/useAddCommentMutation.tsx
  src/hooks/lecture/useGetComments.tsx
  src/hooks/user/useAuth.tsx
  src/hooks/user/useUserName.tsx
  src/redux/slice/classroomModalSlice.tsx
Labels: Feat, team6

#116 Feat: 클래스룸의 강의수정/강의추가 모달창 리팩토링 및 toast 메세지창 렌더링 구현 #110 #111 #112
  public/images/dropzone-border.svg
  src/components/classroomModal/createLecture/AddVideoFileModal.tsx
  src/components/classroomModal/createLecture/DropzoneSection.tsx
  src/hooks/lecture/useVideoFileDrop.tsx
  src/redux/slice/dropzoneFileSlice.tsx
  src/redux/store.tsx
Labels: Feat, Style, Refactor, team6

#109 Update: classroom 모달 강의 생성 중 입력값 유지, 초기화 기능 추가 #88
  src/components/classroomModal/common/LectureSetting.tsx
  src/components/classroomModal/common/LectureTitle.tsx
  src/components/classroomModal/common/ModalSubmitButton.tsx
  src/components/classroomModal/createLecture/AddLinkModal.tsx
  src/components/classroomModal/createLecture/MakeLectureModal.tsx
  src/redux/slice/lectureInfoSlice.tsx
  src/redux/slice/lectureTitleSlice.tsx
  src/redux/slice/linkContentSlice.tsx
  src/redux/store.tsx
Labels: Update, team6

#115 Feat: 답글 기능 구현 및 삭제 기능 구현
  src/components/classroomModal/comment/Comment.tsx
  src/components/classroomModal/comment/CommentForm.tsx
  src/components/classroomModal/comment/ReplySection.tsx
  src/components/lectureRoom/CommentsSection.tsx
  src/components/lectureRoom/LectureComment.tsx
  src/hooks/lecture/useDeleteComment.tsx
  src/redux/slice/classroomModalSlice.tsx
Labels: Feat, team6

#121 Update: 댓글/답글 등록 및 삭제에 따른 랜더링 방식 수정
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/CommentsSection.tsx
  src/hooks/lecture/useAddCommentMutation.tsx
  src/hooks/lecture/useDeleteComment.tsx
  src/hooks/lecture/useGetComments.tsx
Labels: Update, team6

#125 Feat: 클래스룸에서 노트 생성 모달창의 내용 상태관리 및 toast ui editor 툴바 옵션 수정
  src/app/classroom/(components)/modal/common/Layout.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSction.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
Labels: Feat, team6

#127 Feat: 댓글 태그 기능 구현
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/types/firebase.types.ts
  src/utils/highlightTags.tsx
Labels: Feat, Style, team6

#128 Feat: sidebar 섹션 추가
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/aside/CourseList.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/(components)/sidebar/EditButton.tsx
  src/app/classroom/(components)/sidebar/Element.tsx
  src/app/classroom/(components)/sidebar/SectionButton.tsx
  src/app/classroom/(components)/sidebar/SectionHandlerButton.tsx
  src/hooks/classroom/useSelectCourse.ts
  src/hooks/mutation/useCreateCourseMutation.ts
  src/hooks/queries/useGetCourseList.ts
  src/types/firebase.types.ts
Labels: Feat, team6

#138 Feat: assignment validation
  public/images/image-add.svg
  public/images/image-delete.svg
  src/app/assignment/(components)/AssignmentCreat.tsx
  src/app/assignment/(components)/AssignmentCreate.tsx
  yarn.lock
Labels: Feat, team5

#136 Feat: 모달 내 컨텐츠 영역 스크롤 관련 props 처리 및 수정
  public/images/icon_plus_gray.svg
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
Labels: Feat, Style, team5

#140 Refactor: Comment 컴포넌트 리팩토링
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentText.tsx
  src/app/classroom/(components)/modal/comment/EditDeleteButtons.tsx
  src/app/classroom/(components)/modal/comment/ReplyCount.tsx
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
  src/hooks/lecture/useDisplayedComment.ts
  src/hooks/lecture/useHandleClicks.ts
Labels: Refactor, team6

#151 Feat: 클래스룸 모달창에서 서버로 강의 정보 전송을 위한 기본 세팅 구현
  src/app/classroom/(components)/modal/common/ModalFooter.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/common/ModalSubmitButton.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddVideoFileModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/hooks/lecture/useLectureInfo.tsx
  src/redux/slice/lectureInfoSlice.tsx
Labels: bug, Feat, Update, team6

#148 Feat: 댓글, 답글 수정 기능 구현
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/EditDeleteButtons.tsx
  src/app/classroom/(components)/modal/comment/ReadComment.tsx
  src/hooks/mutation/useUpdateComment.ts
Labels: Feat, Refactor, team6
