Repository sniperfactory-official/sfac-lms-team-b, pull requests merged in 2023-08, with the labels that each got.

#153 Style: 강의장에서는 layout 랜더링을 사용하지 않기에 style 수정
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/mutation/useAddComment.ts
Labels: Style, Fix, team6

#145 Update: 기간 설정 timeStamp 타입수정
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/modal/comment/CommentText.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/ReadComment.tsx
  src/app/classroom/(components)/modal/comment/ReplyCount.tsx
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/ModalFooter.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddVideoFileModal.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/(components)/sidebar/EditButton.tsx
  src/app/classroom/(components)/sidebar/Element.tsx
  src/app/classroom/(components)/sidebar/SectionButton.tsx
  src/app/classroom/page.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/classroom/useSelectCourse.ts
  src/hooks/lecture/useDisplayedComment.ts
  src/hooks/lecture/useHandleClicks.ts
  src/hooks/lecture/useLectureInfo.tsx
  src/hooks/mutation/useAddComment.ts
  src/hooks/mutation/useDeleteCourse.ts
  src/hooks/mutation/useUpdateComment.ts
  src/hooks/queries/useGetCourseList.ts
  src/redux/slice/editCourseIdSlice.ts
  src/redux/slice/lectureInfoSlice.tsx
  src/redux/store.tsx
  src/types/firebase.types.ts
  yarn.lock
Labels: Update, team6

#154 Feat: 강의장 헤더 이미지 랜더링 기능 구현
  next.config.js
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/hooks/lecture/useProfileImageURL.ts
Labels: Feat, team6

#142 Feat: 과제 수정 하기 form 생성
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Feat

#143 Feat: 과제 완료여부 데이터처리 및 제출현황 표시(for 학생)
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
Labels: Feat, team5

#165 Update: 강의장 이미지 랜더링 구현
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/ReadComment.tsx
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/hooks/user/useUserProfileImage.ts
Labels: Update, team6

#167 Update: 강의장 유저 Image 랜더링 되는 부분 구현
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/ReadComment.tsx
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/components/Header/Navbar.tsx
  src/hooks/user/useUserProfileImage.ts
Labels: Feat, Update, team6

#168 Feat: 과제 상세 정보 불러오기 및 세부 수정
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/hooks/queries/useGetAssignment.ts
Labels: Feat, team5

#169 !HOTFIX: data 관련 에러 수정
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/types/firebase.types.ts
Labels: !HOTFIX

#171 Feat: 강의장 노트 타입, markdown 기능 구현 (1차)
  package.json
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/NoteLecture.tsx
  tailwind.config.js
  yarn.lock
Labels: Feat, team6

#178 Feat: Content를 제외한 강의 정보(제목,수강기간,비공개여부 등등) 업로드 기능 구현
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/ModalFooter.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/page.tsx
  src/hooks/classroom/useSelectCourse.ts
  src/hooks/lecture/useLectureInfo.tsx
  src/hooks/mutation/useCreateLecture.ts
  src/redux/slice/lectureInfoSlice.tsx
Labels: Feat, Update, team6

#177 Fix: 13버전에 맞지 않는 prop 사용으로 인한 경고 수정
  src/app/classroom/(components)/modal/comment/UserImage.tsx
Labels: Fix, team6

#179 Feat: Sidebar에서 DND로 순서 변경
  package.json
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/(components)/sidebar/DndItem.tsx
  src/app/classroom/page.tsx
  src/components/Header/Navbar.tsx
  src/hooks/classroom/useSelectCourse.ts
  src/hooks/mutation/useDeleteCourse.ts
  src/redux/slice/editCourseIdSlice.ts
  yarn.lock
Labels: Feat, team6

#174 Feat: confirm dialog 작업 외 과제 상세 영역 추가 작업
  src/app/assignment/(components)/AssignmentConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/hooks/mutation/useSubmitAssignment.ts
Labels: Feat, Style, team5

#191 Update: userId & readStudents 값 추가
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/hooks/mutation/useCreateAssignment.ts
Labels: Update, team5

#193 Feat: 과제수정하기 모달과 연결
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Feat

#194 Feat: 피드백생성hook 기능구현 및 과제제출 hook 기능추가
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/hooks/mutation/useCreateFeedback.ts
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/queries/useGetFeedbacks.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, Update, team5

#189 Feat: firebase cloud storage에 이미지 업로드
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/hooks/lecture/useUploadNoteImage.ts
  src/utils/firebase.ts
Labels: Feat, team6

#187 Feat: 댓글의 답글달기 버튼 및 기능 추가
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
Labels: Feat, Style, team6

#185 Update: lecture 생성 후 refetch된 데이터 local state에 동기화작업
  src/app/classroom/page.tsx
  src/hooks/mutation/useCreateCourseMutation.ts
Labels: Feat, Update, team6

#198 Update: 제출한 과제 불러오는 hook 기능수정
  src/app/assignment/[assignmentId]/page.tsx
  src/hooks/mutation/useCreateFeedback.ts
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/mutation/useUpdateFeedback.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, Update, team5

#205 Update: 답글달기 기능 수정 및 유저 이미지 업데이트
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/UserImage.tsx
Labels: Update, team6

#207 Feat: 비디오 타입일 때 강의장 구현 및 이에 따른 함수 Rename
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
  src/hooks/lecture/useGetMediaURL.ts
  src/hooks/lecture/useProfileImageURL.ts
Labels: Feat, Rename, team6

#208 Update: lecture order 추가 및 이슈 사항 처리
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/page.tsx
  src/hooks/mutation/useCreateLecture.ts
  src/hooks/mutation/useDeleteCourse.ts
  src/hooks/queries/useGetCourseList.ts
Labels: Update, team6

#211 Feat: 노트만들기 모달창에서 Content(노트 내용) 업로드 기능 구현
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/hooks/lecture/useLectureInfo.tsx
  src/hooks/mutation/useCreateLecture.ts
  src/redux/slice/lectureInfoSlice.tsx
  src/types/firebase.types.ts
Labels: Feat, Update, team6

#213 Feat: 등록한 과제 디테일 불러오기
  public/images/image_add.svg
  public/images/image_delete.svg
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/queries/useGetAssignment.ts
Labels: Feat

#210 Update: 태그를 강조하는 함수에 타임스탬프도 강조하는 기능 추가
  src/utils/highlightTags.tsx
Labels: Update, team6

#217 Style: confirm dialog 및 피드백 스타일 외 과제 상세 작업 진행중
  public/images/icon_new.svg
  src/app/assignment/(components)/AssignmentConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
Labels: Feat, Style, team5

#214 Fix: 타입스크립트 에러 수정
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
Labels: Fix, team6

#219 Feat: 사이드바 DND 순서 변경
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/(components)/sidebar/SectionButton.tsx
  src/app/classroom/page.tsx
  src/hooks/classroom/useClickOutside.ts
  src/hooks/classroom/useSelectCourse.ts
  src/hooks/mutation/useDeleteCourse.ts
  src/hooks/mutation/useUpdateLectureOrder.ts
  src/redux/slice/editCourseIdSlice.ts
Labels: Feat, team6

#218 Feat: LeftNav에 Dnd 기반 과제순서변경 기능 및 데이터 업데이트 함수 추가
  .vscode/launch.json
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/hooks/mutation/useUpdateAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  tsconfig.json
Labels: Feat, team5

#224 Fix: 불필요한 코드정리 및 라우팅 에러 수정
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
Labels: Fix, team5

#220 Feat: classroom 링크 만들기 모달 입력된 링크 유효성 검사 기능 구현
  package.json
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/hooks/lecture/useLinkValidity.tsx
  yarn.lock
Labels: Update, team6

#226 Fix: 강의장과 관련한 전체적인 타입스크립트 에러 수정
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LinkLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/NoteLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
Labels: Fix, team6

#222 Feat: 비디오 파일 storage 업로드 및 Content(비디오 정보)를 포함한 강의 정보 생성 기능 구현
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddVideoFileModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/hooks/lecture/useDeleteFile.ts
  src/hooks/lecture/useLectureInfo.tsx
  src/hooks/lecture/useUploadFile.ts
  src/hooks/lecture/useUploadNoteImage.ts
  src/hooks/lecture/useVideoFileDrop.tsx
  src/redux/slice/dropzoneFileSlice.tsx
  src/redux/slice/lectureInfoSlice.tsx
Labels: Feat, Update, team6

#227 Feat: 수정된 과제 데이터 저장
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/mutation/useUpdateAssignment.ts
Labels: Feat, team5

#230 Feat: 등록된 과제 삭제하기
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
Labels: Feat, team5

#231 Feat: useUserInfo hook
  src/hooks/user/useUserInfo.tsx
Labels: Feat

#234 Update: 영상 강의 업로드시 업로드상태(업로드중, 업로드완료)에 따라 toast창 다르게 띄우기 #233
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/hooks/lecture/useDeleteFile.ts
  src/hooks/lecture/useUploadFile.ts
  src/hooks/lecture/useUploadImage.ts
  src/hooks/lecture/useUploadVideo.ts
  src/hooks/lecture/useVideoFileDrop.tsx
  src/redux/slice/dropzoneFileSlice.tsx
Labels: Feat, Update, team6

#236 Feat: 이전/다음 강의 기능 구현
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureNavigation.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/NavigationButton.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LectureContent.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/page.tsx
  src/hooks/lecture/useProfileImage.ts
  src/hooks/queries/useGetPreAndNextLectureInfo.ts
Labels: Feat, Refactor, team6

#232 Feat: /classroom 디테일 작업
  public/images/thumnail.png
  src/app/classroom/(components)/ClassContent.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/page.tsx
  src/hooks/classroom/useContentSyncer.ts
  src/utils/convertSecondsToMinute.ts
Labels: Feat, team6

#237 Feat: 과제 상세, 제출 작업 진행중, team5 병합
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/detail/[id]/page.tsx
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, team5

#240 Feat: classroom 강의 삭제 모달 구현 #238
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/modal/createLecture/LectureDeleteModal.tsx
Labels: Feat, team6

#244 Feat: 링크 만들기 모달창에서 링크 정보를 포함한 강의 생성 기능 구현 #175
  src/app/classroom/(components)/modal/common/Layout.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/hooks/lecture/useLectureInfo.tsx
  src/hooks/lecture/useVideoFileDrop.tsx
  src/redux/slice/lectureInfoSlice.tsx
Labels: Feat, Update, team6

#246 Fix: useSubmitAssignment 과제 링크 제출 관련 hook 수정
  src/hooks/mutation/useSubmitAssignment.ts
Labels: Fix

#248 Feat: 강의 목록에서 각 강의 수정 버튼 클릭시 해당 모달창 open 구현
  src/app/classroom/(components)/ClassContent.tsx
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddVideoFileModal.tsx
  src/hooks/lecture/useClassroomModal.tsx
  src/redux/slice/classroomModalSlice.tsx
Labels: Feat, Update, team6

#249 Feat: 댓글창 무한 스크롤
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/CommentsSection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureNavigation.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/NoteLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/page.tsx
  src/app/classroom/page.tsx
  src/components/Header/Navbar.tsx
  src/components/Loading/MiniLoadingSpinner.tsx
  src/hooks/lecture/useObserver.ts
  src/hooks/mutation/useAddComment.ts
  src/hooks/mutation/useDeleteComment.ts
  src/hooks/mutation/useDeleteLecture.ts
  src/hooks/mutation/useUpdateComment.ts
  src/hooks/queries/useGetComment.ts
Labels: Feat, Style, team6

#256 Update: 과제 등록 유효성 검사 및 오류 수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useUpdateAssignment.ts
Labels: Feat, team5

#258 Refactor: 유저 이미지 중복 함수 수정 및 타입 에러 수정
  src/app/classroom/(components)/modal/comment/UserImage.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
Labels: Style, Refactor, Fix, team6

#262 Update: 비공개 여부에 따른 강의장 이동 및 댓글, 답글 모달 닫힘 여부
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LectureContent.tsx
  src/hooks/mutation/useDeleteComment.ts
  src/hooks/queries/useGetPreAndNextLectureInfo.ts
Labels: Update, team6

#270 Style: 모달 컴포넌트 스타일 수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Style

#266 Refactor: CommentForm 컴포넌트 리팩토링
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/CommentsSection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/hooks/lecture/useLectureInfo.ts
  src/hooks/lecture/useSubmitComment.ts
  src/hooks/user/useAuth.tsx
  src/hooks/user/useUser.ts
  src/hooks/user/useUserName.tsx
  src/hooks/user/useUserProfileImage.ts
Labels: Refactor, team6

#277 Feat: 비공개 강의 UI & 사이드 섹션 order 정렬
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/page.tsx
  src/hooks/classroom/useContentSyncer.ts
  src/hooks/mutation/useCreateCourseMutation.ts
  src/hooks/mutation/useDeleteCourse.ts
  src/hooks/queries/useGetCourseList.ts
Labels: Feat, Fix, team6

#272 Refactor: 댓글 조회하는 컴포넌트 및 함수 리팩토링
  src/app/classroom/(components)/contexts/LectureCommentContext.ts
  src/app/classroom/(components)/contexts/LectureCommentProvider.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/CommentsSection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureCommentHeader.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/lecture/useFilterTopLevelComments.ts
  src/hooks/lecture/useGetSelectedCommentAndReplies.ts
  src/hooks/queries/useGetAllComments.ts
  src/hooks/queries/useGetComment.ts
  src/hooks/queries/useGetComments.ts
  tsconfig.json
Labels: Refactor, team6

#273 Feat: 과제 등록 이미지 storage에 저장
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useUpdateImage.ts
Labels: Feat, team5

#282 Refactor: /classroom 리팩토링
  src/app/classroom/(components)/ClassContent.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/main/ContentImg.tsx
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/app/classroom/(components)/main/CourseInfo.tsx
  src/app/classroom/(components)/modal/createLecture/LectureDeleteModal.tsx
  src/app/classroom/(components)/sidebar/CourseList.tsx
  src/app/classroom/(components)/sidebar/EditButton.tsx
  src/app/classroom/(components)/sidebar/LectureList.tsx
  src/app/classroom/page.tsx
  src/hooks/classroom/useClickOutside.ts
  src/hooks/classroom/useCreateSection.ts
  src/hooks/classroom/useEditMode.ts
  src/hooks/classroom/useLectureOrder.ts
  src/hooks/classroom/useModalManage.ts
  src/hooks/classroom/useSelectCourse.ts
Labels: Feat, Fix, team6

#280 Feat: Intl API를 활용한 timestamp formatting
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/utils/emptyArrayCheck.ts
  src/utils/timestampToIntlDate.ts
Labels: Feat, team5

#284 Fix: useSubmit hook 버그 수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/page.tsx
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/mutation/useUpdateFeedback.ts
  src/hooks/mutation/useUpdateSubmittedAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Fix, team5

#288 Feat: drop-zone dragEnter 발생했을 때 스타일 변경
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
Labels: Feat, Style, team5

#290 Update: useUser hook 리턴값 수정 및 userInfo 프롭스 기능수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  src/hooks/user/useUserInfo.tsx
Labels: Update, team5

#292 Style: fix the modal style
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Style, team5

#293 Style: 일부 영역 stretch 적용
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
Labels: Style, team5

#283 Refactor: 강의장 관련한 함수 리팩토링 진행
  src/app/classroom/[lectureId]/(components)/lectureRoom/CommentsSection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/page.tsx
  src/hooks/mutation/useAddComment.ts
  src/hooks/mutation/useDeleteComment.ts
  src/hooks/mutation/useUpdateComment.ts
  src/hooks/queries/useGetAllComments.ts
  src/hooks/queries/useGetLectureInfo.ts
  src/hooks/queries/useGetPreAndNextLectureInfo.ts
Labels: Refactor, team6

#295 Fix: 댓글/답글 수정 시, 콘솔 경고 수정
  src/app/classroom/(components)/modal/comment/EditComment.tsx
Labels: Fix, team6

#296 Feat: 과제수정 이미지 오류 수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/mutation/useUpdateAssignment.ts
Labels: Feat, team5

#297 Feat: 제출한과제 삭제기능 구현
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/hooks/mutation/useDeleteSubmittedAssignment.ts
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/mutation/useUpdateSubmittedAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, team5

#298 Update: Dnd 분기처리 및 활성화 기능 추가
  package.json
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  yarn.lock
Labels: Update, team5

#299 Feat: 과제 파일 제출 기능 외 기존 custom hook 수정
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/hooks/mutation/useSubmitAssignment.ts
  src/hooks/mutation/useUpdateFiles.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, team5

#301 Update: 과제 sidebar Dnd on/off, reset, update, delete 기능 추가
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
  src/app/assignment/page.tsx
  src/hooks/mutation/useDeleteRegisteredAssignmentByAssignmentId.ts
  src/hooks/mutation/useUpdateAssignmentOrder.ts
Labels: Update, team5

#305 Refactor: 토스트 메시지 오류 수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Refactor, team5

#306 Team5 feat/assignment navlist
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
Labels: Update, team5

#303 Update: classroom 모달 내 입력 필수 값 지정 #260
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/LectureTitle.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/redux/slice/lectureInfoSlice.tsx
Labels: Update, team6

#308 Update: classroom 모달 입력 에러메세지 토스트 형식으로 수정 #260
  src/app/classroom/(components)/modal/common/ModalMain.tsx
Labels: Update, team6

#309 Feat: 과제 읽음 퍼센티지 작업
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/hooks/mutation/useUpdateReadStudents.ts
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetStudents.ts
Labels: Feat, team5

#310 Feat: 과제 삭제 hook 기능구현
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
  src/hooks/mutation/useDeleteSubmittedAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Feat, team5

#307 Feat: 이미지 추가
  public/images/cancel.svg
  public/images/submitButton.svg
  public/images/upload.svg
  public/images/화살표.svg
  src/app/community/(components)/CommunityCard.tsx
  src/app/community/(components)/CommunityModal/index.tsx
  src/app/community/(components)/Layout.tsx
  src/app/community/(components)/PostForm/PostForm.tsx
  src/app/community/page.tsx
  src/components/Sidebar.tsx
  src/redux/userSlice.tsx
Labels: Feat, team10

#317 Style: 디자인시스템 DateSelector 적용
  package.json
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/app/layout.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/mutation/useUpdateAssignment.ts
  yarn.lock
Labels: Style, team5

#318 Fix: 타입에러 수정 및 디자인 컴포넌트 세팅
  package.json
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
  yarn.lock
Labels: Fix

#314 Style: 디자인시스템 컴포넌트 반영(과제 상세 외)
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/layout.tsx
  src/components/PageToast.tsx
Labels: Style

#320 Feat: 전역 미들웨어에서 로그인 여부에 따른 리다이렉트 처리
  src/app/api/cookie.ts
  src/app/api/route.ts
  src/app/classroom/[lectureId]/page.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/sign.tsx
  src/components/Header/Navbar.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/reactQuery/navbar/useGetUserQuery.ts
  src/middleware.ts
Labels: Feat, team6

#325 Feat : 클래스룸에서 강의 수정 기능 구현
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/AddVideoFileModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/hooks/lecture/useClassroomModal.tsx
  src/hooks/lecture/useFirebaseLectureSlice.ts
  src/hooks/mutation/useUpdateLecture.ts
  src/redux/slice/classroomModalSlice.tsx
Labels: Feat, Update, team6

#313 Feat: React-player를 사용하여 수강여부를 알기 위해 Progress 활용
  package.json
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LectureContent.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
  src/hooks/mutation/useCreateProgress.ts
  src/hooks/queries/useGetLectureInfo.ts
  src/hooks/queries/useGetProgressInfo.ts
  yarn.lock
Labels: Feat, team6

#326 Update: 충돌해결하면서 생긴 에러 수정
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
Labels: Update

#322 Fix: mypage 수정
  package.json
  src/app/mypage/(components)/Progress.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/components/Header/Navbar.tsx
  src/components/Header/Tab.tsx
  yarn.lock
Labels: Fix, team10

#328 Style: 디자인 시스템 적용
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
Labels: Style, team5

#329 Fix: 과제 버튼 스타일 및 기능수정, Dnd 기능 버그수정, userInfo 수정사항 반영
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/page.tsx
Labels: Fix, team5

#332 Refactor: Dateselector, 유효성 검사 오류
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useCreateAssignment.ts
Labels: Refactor, team5

#335 Style: 디자인시스템 반영
  package.json
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/utils/emptyArrayCheck.ts
  yarn.lock
Labels: Style, team5

#334 Refactor: 테스트 진행 후 오류수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/hooks/mutation/useCreateAssignment.ts
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
  src/hooks/mutation/useDeleteSubmittedAssignment.ts
  src/hooks/mutation/useUpdateAssignment.ts
Labels: Refactor, team5

#337 Update: 제출한 과제 삭제시 reload하게 기능수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
  src/hooks/mutation/useDeleteSubmittedAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Update, team5

#338 Style: 디자인 컴포넌트 적용 및 tailwind 스타일 개선
  src/app/assignment/(components)/AssignmentGlobalConfirmPopup.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
Labels: Style, Update, team5

#341 Update: 강의 수정시 기존 비디오 파일 삭제에 대한 처리 구현
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/hooks/lecture/useDeleteFile.ts
  src/hooks/lecture/useFirebaseLectureSlice.ts
  src/hooks/lecture/useVideoFileDrop.tsx
  src/redux/slice/dropzoneFileSlice.tsx
Labels: Update, team6

#344 Style: 디자인 시스템 적용
  package.json
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/LectureTitle.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/app/layout.tsx
  yarn.lock
Labels: Style, team6

#345 Feat: 강의장, 강의 진행률 기능 구현
  src/app/classroom/(components)/contexts/VideoContext.ts
  src/app/classroom/(components)/contexts/VideoContextProvider.tsx
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/lecture/useDisplayedComment.ts
  src/hooks/lecture/useLectureCompletion.ts
  src/hooks/lecture/useLectureProgress.ts
  src/hooks/mutation/useCreateProgress.ts
  src/hooks/mutation/useUpdateCompletion.ts
  src/hooks/mutation/useUpdateProgress.ts
  src/hooks/queries/useGetProgressInfo.ts
  src/utils/highlightTags.tsx
Labels: Feat, team6

#347 Style: TEAM5 디자인시스템 반영 및 레이아웃 조정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmPopup.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/app/assignment/layout.tsx
  src/app/layout.tsx
Labels: Style, team5

#352 Style: 강의장 디자인 시스템 적용
  package.json
  src/app/classroom/(components)/ClassContent.tsx
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/CommentText.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/ReplyCount.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureCommentHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureNavigation.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/NavigationButton.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LectureContent.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LinkLecture.tsx
  src/app/layout.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/queries/useGetProgressInfo.ts
  yarn.lock
Labels: Style, team6

#353 Feat: 비디오 강의 삭제시 비디오 파일 storage에서 삭제
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/hooks/lecture/useClassroomModal.tsx
  src/redux/slice/classroomModalSlice.tsx
Labels: Feat, Update, team6

#355 Style: 강의 만들기 모달 디자인 시스템 적용 #354
  package.json
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/LectureTitle.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/AddLinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/LectureDeleteModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  tailwind.config.js
  yarn.lock
Labels: Style, team6

#356 Style: 디자인시스템 일부 추가 반영
  package.json
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/globals.css
  yarn.lock
Labels: Style, team5

#357 Team5 작업 병합
  package.json
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/layout.tsx
  yarn.lock
Labels: team5

#359 Team6 병합
  package.json
  src/app/Provider.tsx
  src/app/assignment/layout.tsx
  src/app/classroom/(components)/ClassContent.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/(components)/contexts/VideoContext.ts
  src/app/classroom/(components)/contexts/VideoContextProvider.tsx
  src/app/classroom/(components)/main/ContentCard.tsx
  src/app/classroom/(components)/main/ContentImg.tsx
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/app/classroom/(components)/main/CourseInfo.tsx
  src/app/classroom/(components)/modal/comment/Comment.tsx
  src/app/classroom/(components)/modal/comment/CommentForm.tsx
  src/app/classroom/(components)/modal/comment/CommentText.tsx
  src/app/classroom/(components)/modal/comment/EditComment.tsx
  src/app/classroom/(components)/modal/comment/ReplyCount.tsx
  src/app/classroom/(components)/modal/comment/ReplySection.tsx
  src/app/classroom/(components)/modal/comment/UserInfo.tsx
  src/app/classroom/(components)/modal/common/LectureSetting.tsx
  src/app/classroom/(components)/modal/common/LectureTitle.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/LectureDeleteModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureComment.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureCommentHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureHeader.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/LectureNavigation.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/NavigationButton.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LectureContent.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/LinkLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/TypeOfLecture.tsx
  src/app/classroom/[lectureId]/(components)/lectureRoom/typesOf/VideoLecture.tsx
  src/app/layout.tsx
  src/components/Header/Navbar.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/lecture/useClassroomModal.tsx
  src/hooks/lecture/useDeleteFile.ts
  src/hooks/lecture/useDisplayedComment.ts
  src/hooks/lecture/useFirebaseLectureSlice.ts
  src/hooks/lecture/useLectureCompletion.ts
  src/hooks/lecture/useLectureProgress.ts
  src/hooks/lecture/useVideoFileDrop.tsx
  src/hooks/mutation/useCreateProgress.ts
  src/hooks/mutation/useUpdateCompletion.ts
  src/hooks/mutation/useUpdateProgress.ts
  src/hooks/queries/useGetProgressInfo.ts
  src/redux/slice/classroomModalSlice.tsx
  src/redux/slice/dropzoneFileSlice.tsx
  src/utils/highlightTags.tsx
  tailwind.config.js
  yarn.lock
Labels: team6

#360 Team5 작업본 수정 병합
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/hooks/mutation/useDeleteFeedback.ts
  src/hooks/queries/useGetAssignment.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
  src/hooks/queries/useSubmittedAssignment.ts
Labels: team5

#361 Style: 일부 레이아웃시프트 관련 수정 적용
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
Labels: team5

#363 Style: 강의 만들기 모달 디자인 시스템 적용 #354
  src/app/classroom/(components)/modal/common/ModalFooter.tsx
  src/app/classroom/(components)/modal/common/ModalMain.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  yarn.lock
Labels: Style, team6

#364 Refactor: B팀 환경에 코드 리팩토링 1차
  src/app/mypage/(components)/AssignmentsDetailModal.tsx
  src/app/mypage/(components)/Category.tsx
  src/app/mypage/(components)/CommentsDetailModal.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/hooks/mypage/useGetAssignments.ts
  src/hooks/queries/useGetProgressInfo.ts
Labels: enhancement

#365 Refactor: B팀 환경에 코드 리팩토링 2차
  public/images/inputMessage.svg
  src/app/community/(components)/CommunityModal/CommentInput.tsx
  src/app/community/(components)/CommunityModal/CommunityModal.tsx
  src/app/mypage/(components)/AssignmentsDetailModal.tsx
  src/app/mypage/(components)/Category.tsx
  src/app/mypage/(components)/CommentsDetailModal.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/hooks/mypage/useGetAssignments.ts
  src/utils/uploadStorageImages.ts
Labels: enhancement, Fix

#367 Refactor: B팀 환경에 코드 리팩토링
  public/images/inputMessage.svg
  public/images/logout.svg
  public/images/noPostingMessage.svg
  src/app/community/(components)/CommunityModal/CommentInput.tsx
  src/app/community/(components)/CommunityModal/CommunityCommentMention.tsx
  src/app/community/(components)/CommunityModal/CommunityModal.tsx
  src/app/community/(components)/CommunityModal/ImageModal.tsx
  src/app/community/(components)/CommunityModal/PostCard.tsx
  src/app/community/(components)/Layout.tsx
  src/app/mypage/(components)/AssignmentsDetailModal.tsx
  src/app/mypage/(components)/Category.tsx
  src/app/mypage/(components)/CommentsDetailModal.tsx
  src/app/mypage/(components)/Profile.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/hooks/community/useGetPostImage.ts
  src/hooks/mypage/useGetAssignments.ts
  src/hooks/queries/useGetProgressInfo.ts
  src/utils/uploadStorageImages.ts
Labels: enhancement, Fix

#371 Update: 타입 및 toast, 제출한과제 삭제 기능수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/page.tsx
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Update, team5

#372 Update: storage 동일 파일명 overwriting 이슈로 독립적인 파일명으로 변경 후 업로드로 변경 외
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/community/(components)/CommunityCard.tsx
  src/app/community/(components)/CommunityModal/PostCard.tsx
Labels: Feat, Style, Fix, team5

#373 Update: 파편화된 confirm dialog 통합 작업 외
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmPopup.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/layout.tsx
  src/app/globals.css
  src/app/mypage/(components)/Profile.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/components/GlobalToast.tsx
  src/components/Header/Navbar.tsx
  src/components/Loading/Loading.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/PageToast.tsx
  src/components/RequireAuth/RequireAuth.tsx
Labels: Refactor

#374 Refactor: DatePicker 초기화 및 예외처리
  src/app/assignment/(components)/AssignmentCreate.tsx
Labels: Refactor, team5

#375 Fix: 퍼센티지 계산식에서 값을 제대로 못 받아오는 문제 때문에 비동기 수정 외 리팩토링
  public/images/noPostingMessage.svg
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/app/community/(components)/CommunityList.tsx
Labels: Refactor, team5

#376 Style: 과제 사이드바 margin 변경, hover 스타일 및 스크롤바 추가
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/layout.tsx
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Style, team5

#378 Update: 피드백 타입 수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentFeedbackContent.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentListSubButton.tsx
  src/app/assignment/(components)/AssignmentStudentViewCard.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCardWrapper.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/page.tsx
  src/app/classroom/(components)/sidebar/SectionButton.tsx
  src/app/mypage/(components)/Progress.tsx
  src/hooks/mutation/useUpdateLectureOrder.ts
  src/hooks/mypage/useGetAssignments.ts
  src/hooks/queries/useGetFeedbacks.ts
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Update, team5

#379 Update: 피드백 타입수정
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/hooks/queries/useGetFeedbacks.ts
Labels: Update, team5

#377 Refactor: LeftNav return에 분기처리된 부분 하나로 통합 및 자동스크롤 기능 추가
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/hooks/queries/useGetSubmittedAssignment.ts
Labels: Refactor, team5

#380 Refactor: 과제 생성 후 생성된 과제 상세 페이지로 이동
  src/app/assignment/(components)/AssignmentCreate.tsx
Labels: Refactor, team5

#381 Update: hover 스타일링 수정 및 drag시 opacity 효과설정
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
Labels: Update, team5

#382 Update: 이미지 업로드시 파일명 반복안되게 기능수정
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/hooks/mutation/useDeleteFeedback.ts
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
  src/hooks/mutation/useDeleteRegisteredAssignmentByAssignmentId.ts
  src/hooks/mutation/useUpdateAssignment.ts
  src/hooks/mutation/useUpdateAssignmentOrder.ts
  src/hooks/mutation/useUpdateFeedback.ts
  src/hooks/queries/useGetAssignment.ts
Labels: Update, team5

#383 Refactor: Team5 리팩토링 작업 병합
  public/images/noPostingMessage.svg
  src/app/assignment/(components)/AssignmentCreate.tsx
  src/app/assignment/(components)/AssignmentDetailContent.tsx
  src/app/assignment/(components)/AssignmentFeedback.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentGlobalConfirmPopup.tsx
  src/app/assignment/(components)/AssignmentLeftNav.tsx
  src/app/assignment/(components)/AssignmentLeftNavContent.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentButton.tsx
  src/app/assignment/(components)/AssignmentLeftNavContentCard.tsx
  src/app/assignment/(components)/AssignmentListContent.tsx
  src/app/assignment/(components)/AssignmentLocalConfirmDialog.tsx
  src/app/assignment/(components)/AssignmentModal.tsx
  src/app/assignment/(components)/AssignmentProfileImage.tsx
  src/app/assignment/(components)/AssignmentStudentViewCardWrapper.tsx
  src/app/assignment/(components)/AssignmentSubmitWithFile.tsx
  src/app/assignment/(components)/AssignmentSubmitWithLink.tsx
  src/app/assignment/(components)/AssignmentTeacherViewCard.tsx
  src/app/assignment/(components)/AssignmentUpdate.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/layout.tsx
  src/app/community/(components)/CommunityCard.tsx
  src/app/community/(components)/CommunityList.tsx
  src/app/community/(components)/CommunityModal/PostCard.tsx
  src/app/globals.css
  src/app/mypage/(components)/Profile.tsx
  src/app/mypage/(components)/UserActivityList.tsx
  src/components/GlobalToast.tsx
  src/components/Header/Navbar.tsx
  src/components/Loading/Loading.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/PageToast.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/hooks/mutation/useDeleteFeedback.ts
  src/hooks/mutation/useDeleteRegisteredAssignment.ts
  src/hooks/mutation/useDeleteRegisteredAssignmentByAssignmentId.ts
  src/hooks/mutation/useUpdateAssignment.ts
  src/hooks/mutation/useUpdateAssignmentOrder.ts
  src/hooks/mutation/useUpdateFeedback.ts
  src/hooks/queries/useGetAssignment.ts
Labels: Refactor, team5

#388 Refactor: 토스트UI 품질 개선, 커뮤니티 글등록버튼 transition 적용
  package.json
  src/app/community/(components)/Inputbar.tsx
  src/components/PageToast.tsx
  tailwind.config.js
  yarn.lock
Labels: Refactor, team5

#392 Refactor : 비디오 파일 저장위치 및 브래드크럼 개선
  src/app/classroom/(components)/modal/common/ModalHeader.tsx
  src/app/classroom/(components)/modal/createLecture/LinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/VideoFileModal.tsx
  src/hooks/lecture/useFirebaseLectureSlice.ts
  src/hooks/lecture/useUploadVideo.ts
Labels: Refactor, team6

#393 Refactor: Team6 리팩토링 작업 병합
  src/app/classroom/(components)/main/ContentInfo.tsx
  src/app/classroom/(components)/modal/common/Layout.tsx
  src/app/classroom/(components)/modal/common/ModalHeader.tsx
  src/app/classroom/(components)/modal/createLecture/AddNoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/LinkModal.tsx
  src/app/classroom/(components)/modal/createLecture/MakeLectureModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteModal.tsx
  src/app/classroom/(components)/modal/createLecture/NoteSection.tsx
  src/app/classroom/(components)/modal/createLecture/VideoFileModal.tsx
  src/hooks/classroom/useModalManage.ts
  src/hooks/lecture/useFirebaseLectureSlice.ts
  src/hooks/lecture/useUploadVideo.ts
  src/utils/convertSecondsToMinute.ts
Labels: Refactor, team6
